sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: vincent712521
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5tHzX4fMjySKcCoCvYci
    access-key-secret: vPKhVa4Kux8jUP6fU4614CQ3FW0wiC
    bucket-name: cangqiongwaimaipbj
  redis:
    host: localhost
    port: 6379
    password: vincent712521
    database: 10
  wechat:
    appid: wx6ef8a4dc2c747116
    secret: 9c784ac31a785dc844979d93e1b15f2a
